# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "usb_storage" "sdhci_pci" ];
      kernelModules = [ "tun" ];
    };
    kernelModules = [ ];
    kernelParams = [ "apple_dcp.show_notch=1" ];
    extraModulePackages = [ ];
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = false;
    };
    binfmt.emulatedSystems = [ "x86_64-linux" "i686-linux" ];
  };

  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
    defaultNetwork.settings.dns_enabled = true;
  };
  
	hardware = {
		asahi = {
			peripheralFirmwareDirectory = ./firmware;
			setupAsahiSound = true;
		};
		graphics.enable = true;
    bluetooth.enable = true;
	};

	networking = {
		hostName = "nixos";
		networkmanager = {
      enable = true;
      wifi.macAddress = "preserve";
      settings = {
        connectivity = {
          uri = "http://nmcheck.gnome.org/check_network_status.txt";
          interval = 300;
        };
        main = {
          rc-manager = "resolvconf";
        };
      };
    };
	};

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/08405f9b-dec5-489b-a862-173e10c9a989";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8722-1E01";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
